name: MapUpdater
main: tk.projectcraftmc.updater.UpdaterMain
author: Eelek
version: 1.1
description: Map updater for ProjectCraft Map
api-version: 1.13

commands:
  updatemap:
    description: dev
  setcompression:
    description: dev
  clearcache:
    description: dev